# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOSTS=%
      - MYSQL_DATABASE=ComparisonData
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_USER=nico
      - MYSQL_PASSWORD=RealPassw0rd
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
